cask_args appdir: '/Applications'

brew 'fish'
brew 'git'
brew 'jo'
brew 'jq'
brew 'mas'

cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'karabiner-elements'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'xquartz'
cask 'dropbox'
